[package]
name = "git-sg"
version = "0.2.1"
edition = "2024"
license = "MIT"
description = "Tool for opening the current git repository in Sourcegraph"
readme = "README.md"
homepage = "https://github.com/Niraj-Fonseka/git-sg"
repository = "https://github.com/Niraj-Fonseka/git-sg"
keywords = ["cli", "web", "git"]
categories = ["command-line-utilities"]


[dependencies]
open = "3.2.0"
dirs = "5.0"
url = "2.5.7"